#category:
#    pattern:  /
#    defaults: { _controller: "AcmeHandmadeBundle:Category:index" }

category_show:
    pattern:  /{slug}/show
    defaults: { _controller: "AcmeHandmadeBundle:Category:show" }