#product:
#    pattern:  /
#    defaults: { _controller: "AcmeHandmadeBundle:Product:index" }

product_show:
    pattern:  /{slug}/show
    defaults: { _controller: "AcmeHandmadeBundle:Product:show" }