product:
    pattern:  /
    defaults: { _controller: "AcmeHandmadeBundle:Product:index" }

product_show:
    pattern:  /{slug}/show
    defaults: { _controller: "AcmeHandmadeBundle:Product:show" }

product_new:
    pattern:  /new
    defaults: { _controller: "AcmeHandmadeBundle:Product:new" }

product_create:
    pattern:  /create
    defaults: { _controller: "AcmeHandmadeBundle:Product:create" }
    requirements: { _method: post }

product_edit:
    pattern:  /{slug}/edit
    defaults: { _controller: "AcmeHandmadeBundle:Product:edit" }

product_update:
    pattern:  /{slug}/update
    defaults: { _controller: "AcmeHandmadeBundle:Product:update" }
    requirements: { _method: post|put }

product_delete:
    pattern:  /{slug}/delete
    defaults: { _controller: "AcmeHandmadeBundle:Product:delete" }
    requirements: { _method: post|delete }
