acme_handmade_homepage:
    pattern:  /
    defaults: { _controller: AcmeHandmadeBundle:Default:index }

AcmeHandmadeBundle_category:
    resource: "@AcmeHandmadeBundle/Resources/config/routing/category.yml"
    prefix:   /category

AcmeHandmadeBundle_product:
    resource: "@AcmeHandmadeBundle/Resources/config/routing/product.yml"
    prefix:   /product



# API
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

acme_handmade_api:
    type: rest
    prefix: /api
    resource: "@AcmeHandmadeBundle/Resources/config/routing/api.yml"


# WSSE
ctm_ml_wsse_login:
    pattern: /wsse/login
    defaults: { _controller: FOSUserBundle:Security:login }

ctm_ml_wsse_check:
    pattern: /wsse/login_check
    defaults: { _controller: FOSUserBundle:Security:check }
    requirements: { _method: post }