acme_handmade_homepage:
    pattern:  /
    defaults: { _controller: AcmeHandmadeBundle:Default:index }

AcmeHandmadeBundle_category:
    resource: "@AcmeHandmadeBundle/Resources/config/routing/category.yml"
    prefix:   /category

AcmeHandmadeBundle_product:
    resource: "@AcmeHandmadeBundle/Resources/config/routing/product.yml"
    prefix:   /product


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

acme_handmade_api_category:
    type: rest
    prefix: /api
    resource: "@AcmeHandmadeBundle/Resources/config/routing/api/category.yml"

