acme_handmade_homepage:
    pattern:  /
    defaults: { _controller: AcmeHandmadeBundle:Default:index }

AcmeHandmadeBundle_category:
    resource: "@AcmeHandmadeBundle/Resources/config/routing/category.yml"
    prefix:   /category

AcmeHandmadeBundle_product:
    resource: "@AcmeHandmadeBundle/Resources/config/routing/product.yml"
    prefix:   /product


# API
acme_handmade_api:
    type: rest
    prefix: /api
    resource: "@AcmeHandmadeBundle/Resources/config/routing/api.yml"

cart:
    pattern:  /cart
    defaults: { _controller: AcmeHandmadeBundle:Cart:show }

cart_clear:
    pattern:  /cart/clear
    defaults: { _controller: AcmeHandmadeBundle:Cart:clear }

cart_product_add:
    pattern:  /cart/add-product/{id}
    defaults: { _controller: AcmeHandmadeBundle:Cart:add }

cart_product_delete:
    pattern:  /cart/delete-product/{id}
    defaults: { _controller: AcmeHandmadeBundle:Cart:delete }

cart_sum:
    pattern:  /cart/sum
    defaults: { _controller: AcmeHandmadeBundle:Cart:sum }