acme_handmade_homepage:
    pattern:  /
    defaults: { _controller: AcmeHandmadeBundle:Default:index }

AcmeHandmadeBundle_category:
    resource: "@AcmeHandmadeBundle/Resources/config/routing/category.yml"
    prefix:   /category

AcmeHandmadeBundle_product:
    resource: "@AcmeHandmadeBundle/Resources/config/routing/product.yml"
    prefix:   /product


api_categories:
    prefix: api/category
    type: rest
    resource: "Acme\HandmadeBundle\Controller\ApiController"