parameters:
#    acme_handmade.example.class: Acme\HandmadeBundle\Example

services:
#    acme_handmade.example:
#        class: %acme_handmade.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
